service: 'product-service'
frameworkVersion: '2'
custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  dbConfig:
    PG_HOST: "lesson4.cnitagnbogml.eu-west-1.rds.amazonaws.com"
    PG_PORT: 5432
    PG_DATABASE: "postgres"
    PG_USERNAME: "postgres"
    PG_PASSWORD: "xKTrsGcaoUmSrMpuGOjw"
plugins:
  - serverless-webpack
provider:
  name: 'aws'
  runtime: 'nodejs14.x'
  region: 'eu-west-1'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    PG_HOST: "${self:custom.dbConfig.PG_HOST}"
    PG_PORT: "${self:custom.dbConfig.PG_PORT}"
    PG_DATABASE: "${self:custom.dbConfig.PG_DATABASE}"
    PG_USERNAME: "${self:custom.dbConfig.PG_USERNAME}"
    PG_PASSWORD: "${self:custom.dbConfig.PG_PASSWORD}"
  lambdaHashingVersion: '20201221'
functions:
  getAll:
    handler: 'src/handlers/products/getAll.getAll'
    timeout: 20
    events:
      - http:
          method: 'get'
          path: 'films'
          cors: true
  getByID:
    handler: 'src/handlers/products/getByID.getByID'
    events:
      - http:
          method: 'get'
          path: 'films/{id}'
          cors: true
